name: Build and publish pypi package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo 📘
      uses: actions/checkout@v3

    - name: Set up Python 3.10 🐍
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install tools 🛠️
      run: |-
        sudo apt-get install --yes make
        python -m pip install setuptools twine wheel

    - name: Update CHANGELOG with release 📋
      if: startsWith(github.ref, 'refs/tags')
      run: |-
        bin/parse-changelog --release "${GITHUB_REF_NAME:1}"

    - name: Commit the CHANGELOG 💾
      if: startsWith(github.ref, 'refs/tags')
      run: |-
        if ! git diff -s --exit-code CHANGELOG.md; then
          git config user.name github-actions;
          git config user.email github-actions@github.com;
          git add CHANGELOG.md;
          git commit -m "Update CHANGELOG for new release";
          git push;
        fi

    - name: Build package 📦
      run: >-
        make package

    - name: Publish package to PyPI 🎁
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
